### PR TITLE
Move OS-specific logic into separate files

### LINKED ISSUE #780: 1.19.0 doesn't work in Windows
When i try to get yab `go get -u github.com/yarpc/yab`, it failed with error:

```
# github.com/uber/tchannel-go/thrift/gen-go/meta
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:79:20: not enough arguments in call to oprot.Flush
        have ()
        want (context.Context)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:103:15: assignment mismatch: 2 variables but error2.Read returns 1 values
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:152:20: not enough arguments in call to oprot.Flush
        have ()
        want (context.Context)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:176:15: assignment mismatch: 2 variables but error4.Read returns 1 values
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:225:20: not enough arguments in call to oprot.Flush
        have ()
        want (context.Context)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:249:15: assignment mismatch: 2 variables but error6.Read returns 1 values
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:295:31: cannot use &metaProcessorHealth literal (type *metaProcessorHealth) as type thrift.TProcessorFunction in assignment:
        *metaProcessorHealth does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:296:34: cannot use &metaProcessorThriftIDL literal (type *metaProcessorThriftIDL) as type thrift.TProcessorFunction in assignment:
        *metaProcessorThriftIDL does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:297:36: cannot use &metaProcessorVersionInfo literal (type *metaProcessorVersionInfo) as type thrift.TProcessorFunction in assignment:
        *metaProcessorVersionInfo does not implement thrift.TProcessorFunction (wrong type for Process method)
                have Process(int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
                want Process(context.Context, int32, thrift.TProtocol, thrift.TProtocol) (bool, thrift.TException)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:307:27: not enough arguments in call to processor.Process
        have (int32, thrift.TProtocol, thrift.TProtocol)
        want (context.Context, int32, thrift.TProtocol, thrift.TProtocol)
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\thrift\gen-go\meta\meta.go:307:27: too many errors
# github.com/uber/tchannel-go
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\connection.go:931:33: undefined: getSendQueueLen
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\connection.go:932:32: undefined: unix.GetsockoptInt
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\connection.go:932:60: undefined: unix.SOL_SOCKET
..\..\pkg\mod\github.com\uber\tchannel-go@v1.19.0\connection.go:932:77: undefined: unix.SO_SNDBUF
```

It works with `tchannel-go@1.17.0`

### PR DESCRIPTION
**Pull request by prashantv**
While we don't officially support non-Linux/Darwin builds
we should still keep the OS-specific logic in separate files
and follow best practices.

Fixes #780.

### CODE REVIEW

**Comment by witriew** [comment]
> we should still keep the OS-specific logic in separate files

Should we enable Travis CI for non-Linux OSes, then?

**Comment by alxn** [comment]
> While we don't officially support non-Linux/Darwin builds
> we should still keep the OS-specific logic in separate files
> and follow best practices.
> 
> Fixes #780.

Look forward to the Windows PR.

**Comment by prashantv** [comment]
> > we should still keep the OS-specific logic in separate files
> 
> Should we enable Travis CI for non-Linux OSes, then?

I was thinking we should use GitHub actions in the future, some of our OSS libraries have already been moved. As part of that, if we can run tests for Darwin, that would be useful.
